//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSCRMSL_UN.CRM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSUpdateFSoap", Namespace="http://unifiedNetwork.com.mx/")]
    public partial class WSUpdateF : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEnvioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSUpdateF() {
            this.Url = global::WSCRMSL_UN.Properties.Settings.Default.WSCRMSL_UN_CRM_WSUpdateF;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateFacturaCompletedEventHandler UpdateFacturaCompleted;
        
        /// <remarks/>
        public event UpdateEnvioCompletedEventHandler UpdateEnvioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unifiedNetwork.com.mx/UpdateFactura", RequestNamespace="http://unifiedNetwork.com.mx/", ResponseNamespace="http://unifiedNetwork.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateFactura(string facturaGuId, string custId) {
            object[] results = this.Invoke("UpdateFactura", new object[] {
                        facturaGuId,
                        custId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateFacturaAsync(string facturaGuId, string custId) {
            this.UpdateFacturaAsync(facturaGuId, custId, null);
        }
        
        /// <remarks/>
        public void UpdateFacturaAsync(string facturaGuId, string custId, object userState) {
            if ((this.UpdateFacturaOperationCompleted == null)) {
                this.UpdateFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateFacturaOperationCompleted);
            }
            this.InvokeAsync("UpdateFactura", new object[] {
                        facturaGuId,
                        custId}, this.UpdateFacturaOperationCompleted, userState);
        }
        
        private void OnUpdateFacturaOperationCompleted(object arg) {
            if ((this.UpdateFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateFacturaCompleted(this, new UpdateFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://unifiedNetwork.com.mx/UpdateEnvio", RequestNamespace="http://unifiedNetwork.com.mx/", ResponseNamespace="http://unifiedNetwork.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateEnvio(string envioGuId, string shipId) {
            object[] results = this.Invoke("UpdateEnvio", new object[] {
                        envioGuId,
                        shipId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEnvioAsync(string envioGuId, string shipId) {
            this.UpdateEnvioAsync(envioGuId, shipId, null);
        }
        
        /// <remarks/>
        public void UpdateEnvioAsync(string envioGuId, string shipId, object userState) {
            if ((this.UpdateEnvioOperationCompleted == null)) {
                this.UpdateEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEnvioOperationCompleted);
            }
            this.InvokeAsync("UpdateEnvio", new object[] {
                        envioGuId,
                        shipId}, this.UpdateEnvioOperationCompleted, userState);
        }
        
        private void OnUpdateEnvioOperationCompleted(object arg) {
            if ((this.UpdateEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEnvioCompleted(this, new UpdateEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateFacturaCompletedEventHandler(object sender, UpdateFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateEnvioCompletedEventHandler(object sender, UpdateEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591